config/routes.rb
Rails.application.routes.draw do
  get 'videos/index'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :videos
  get 'pages/about'

  get 'pages/contact'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :wistia, presence: true
    validates :description, presence: true,
                            length: { minimum: 10, maximum: 400 }
    validates :title, presence: true,
                      length: { minimum: 4, maximum: 20 }
    

	def next
       Video.where("id > ?", id).first
	end

	def prev
       Video.where("id < ?", id).last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to videos_path
  	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = Video.all

    @next_video = @video.next
    @prev_video = @video.prev
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :wistia, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome | Online Ed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
<!-- add icons library -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
<!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>          
</head>
<body>
	<nav>
      <div class="nav-wrapper">
        <%= link_to "OnlinED Platform", root_path, class: "brand-logo center" %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i></a></li>
          <li><a href="<%= pages_about_path %>"><i class="material-icons">&#xE55A;</i>About</a></li>
          <li><a href="<%= pages_contact_path %>"><i class="material-icons">&#xE0C8;</i>Contact</a></li>
          <li><a href="<%= rails_admin_path %>"><i class="material-icons">&#xE897;</i>Admin panel</a></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i></a></li>
          <li><a href="<%= pages_about_path %>"><i class="material-icons">&#xE55A;</i>About</a></li>
          <li><a href="<%= pages_contact_path %>"><i class="material-icons">&#xE0C8;</i>Contact</a></li>
          <li><a href="<%= rails_admin_path %>"><i class="material-icons">&#xE897;</i></i>Admin panel</a></li>
        </ul>
      </div>
  </nav>

	<div class="row">
	   <div class="col s12">
   
   <% if current_user %>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
   <% else %>
      <%= link_to "login", new_user_session_path %>
   <% end %>
     
	   	
<%= yield %>

      </div>
    </div>
<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
      <script>
         $('.button-collapse').sideNav();
      </script>
</body>
</html>

app/views/pages/about.html.erb
 <h5>About Me</h5>

<div class="card z-depth-4">
    <!--twitter feed-->
	<div class="card-content white-text">
		<div class="col m6">
		<a class="twitter-timeline" href="https://twitter.com/becracra" data-widget-id="633829586711773185">Tweets by @becracra</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
         </div>
		<!--twitter avatar-->
		<div class="col m6">
		   <div class="card-panel grey lighten-4 z-depth-1">
		   	  <div class="row valign-wrapper">
		   	  	 <!--img avatar-->
		   	  	 <div class="col m3">
		   	  	 	<%= image_tag "desipic.jpg", class: "circle responsive-img" %>
		   	  	 </div>
		   	  	 <!--text-->
		   	  	 <div class="col m9">
		   	  	 	<span class="black-text">
		   	  	 		This is where I usually talk a lot.....
		   	  	 	</span>
		   	  	 </div>
		   	  </div>
		   </div>
			
		</div>
	</div>
</div>

app/views/pages/contact.html.erb
<h5>Contacts</h5> 

<div class="card z-depth-3">
	<div class="card-content">
      <p>Email: desiby@hotmail.com</p><br/>
	    <p>Find me on the map</p><br/>
		    <div id="map"></div>

	</div>
</div>

     

<style>
      #map {
        width: 100%;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map');
        var mapOptions = {
          center: new google.maps.LatLng(25.79	, -80.13),
          zoom: 14,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
        var marker = new google.maps.Marker({

        position: new google.maps.LatLng(25.79 , -80.13),
        title: "south beach"
        });

        marker.setMap(map);
     }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h4 id="error"><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h4>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
   
    <%= f.text_field :wistia, :placeholder => "link", :length => "10" %>
  </div>
  <div class="input-field">
    
    <%= f.text_field :title, :placeholder => "Title", :length => "20" %>
  </div>
  <div class="input-field">
    
    <%= f.text_area :description, :placeholder => "Description", :length => "400", class: "materialize-textarea"%>
  </div>
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
    <!--<a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>-->
    <%= link_to "Back", videos_path, class: "btn waves-effect waves-light" %>
<% end %>

app/views/videos/edit.html.erb
<h2>Editing Video</h2>

<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Video Lessons</h2>

  <%= link_to new_video_path, class: "btn-floating btn-large waves-effect waves-light red" do %>
  <i class="material-icons">add</i>
  <% end %>
 
 <ul class="collapsible popout" data-collapsible="accordion">
    <% @videos.each do |video| %>
    <li>
      <div class="collapsible-header">
       <i class="material-icons">description</i>
        <%= link_to video.title, video %>
        <!-- 
        <span class="right">
           <%=link_to edit_video_path(video) do %> 
            <i class="material-icons">edit</i><% end %>
               <%=link_to video, method: :delete, data: { confirm: "are you sure"} do %>
              <i class="material-icons">delete</i><% end %>
              -->
          
        </span>
      </div>
      <div class="collapsible-body"><p><%= video.description %></p></div>
    </li>
    <% end %>
</ul>

app/views/videos/new.html.erb
<h1>New Video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row " >
   <div class="col m3 z-depth-1">
	  <div class="collection">
	  <% @videos.each do |video| %>
	    <%= link_to video.title, video, class: "collection-item" %>
	  <% end %>
      </div>
	</div>
	<div class="col m9">
		<div class="card blue-grey darken-1">
			   <div class="card-image">
			   	  <div id="wistia_<%= @video.wistia %>"></div>
			   </div>
	            <div class="card-content white-text">
		             <button class="btn btn primary" onclick="setPlaySpeed(0.75)">0.75x</button>
		             <button class="btn btn primary" onclick="setPlaySpeed(1)">1x</button>
		             <button class="btn btn primary" onclick="setPlaySpeed(1.25)">1.25x</button>
		             <button class="btn btn primary" onclick="setPlaySpeed(2)">2x</button>
		              <span class="card-title"><%= @video.title %></span>
		              <p><%= @video.description %></p>
	            </div>
            <div class="card-action">
              <%= link_to "Previous", @prev_video if !@prev_video.nil? %>
              <span class ="right">
              <%= link_to "Next", @next_video if !@next_video.nil? %>
              </span>
            </div>
          </div>
	</div>
</div>

<script src="http://fast.wistia.net/static/E-v1.js"></script>
<script>
wistiaEmbed = Wistia.embed("<%= @video.wistia %>", {
  videoQuality: "hd-only",
  videoFoam: true
});

function setPlaySpeed(speed) {
   wistiaEmbed.playbackRate(speed);
}
</script>